
    drop table DataPoint if exists;

    drop table DataPoint_AUD if exists;

    drop table REVINFO if exists;

    create table DataPoint (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table DataPoint_AUD (
        id bigint not null,
        REV integer not null,
        REVTYPE tinyint,
        name varchar(255),
        primary key (id, REV)
    );

    create table REVINFO (
        REV integer generated by default as identity,
        REVTSTMP bigint,
        primary key (REV)
    );

    alter table DataPoint_AUD 
        add constraint FK_7pdslro8w1n74eqwmorrn0hnb 
        foreign key (REV) 
        references REVINFO;
